services:
  payload-template-pg:
    image: ghcr.io/m6o4/payload-template:latest
    container_name: payload-template-pg
    restart: unless-stopped
    networks:
      - m6o4-prd-network
    env_file:
      - stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payload-template-pg.rule=Host(`payload-template-pg.s3.co.ke`)"
      - "traefik.http.routers.payload-template-pg.entrypoints=websecure"
      - "traefik.http.routers.payload-template-pg.tls.certresolver=letsencrypt"
      - "traefik.http.services.payload-template-pg.loadbalancer.server.port=3000"

networks:
  m6o4-prd-network:
    external: true
    name: m6o4-prd-network
